---
trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-24.04"

variables:
  azureServiceConnection: "sc-hestia-poc-staging"
  dockerRegistryServiceConnection: "sc-hestia-acr"
  acrName: "acrpochestiaaks.azurecr.io"
  imageRepository: "hestia-loyalty"
  k8sNamespace: "hestia-staging"
  azureResourceGroup: "rg_poc_hestia_aks-staging"
  k8sCluster: "k8s-cluster-staging"

stages:
  - stage: Build
    displayName: Build Publish Docker Docker Image to ACR

    jobs:
      - job: build_and_push
        displayName: Build & Push Docker Image
        steps:
          - bash: git clone https://$GITHUB_TOKEN@github.com/DonMarax/Hestia-loyalty.git app-code
            displayName: "Clone of Next.js application"
            env:
              GITHUB_TOKEN: $(GITHUB_TOKEN)

          - task: Docker@2
            inputs:
              command: "buildAndPush"
              Dockerfile: "app-code/Dockerfile"
              buildContext: "app-code"
              tags: |
                $(Build.SourceVersion)
                latest
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "kubernetes"
              artifact: "k8s-manifests"
              publishLocation: "pipeline"

  - stage: Deploy
    displayName: Deploy Image to AKS
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: deploy_to_aks
        displayName: Deploy Artifact to AKS
        steps:
          - download: current
            artifact: "k8s-manifests"

          - bash: sed -i 's|__IMAGE_TAG__|$(Build.SourceVersion)|g' $(Pipeline.Workspace)/k8s-manifests/deployment.yml

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                # Récupérer l'ID Client de l'identité du secrets-provider sur AKS
                CLIENT_ID=$(az aks show --resource-group $(azureResourceGroup) --name $(k8sCluster) --query addonProfiles.azureKeyvaultSecretsProvider.identity.clientId -o tsv)

                # Récupérer le Tenant ID de l'abonnement Azure actif
                TENANT_ID=$(az account show --query tenantId -o tsv)

                # Remplacer les placeholders dans le manifeste Kubernetes
                sed -i "s|__IDENTITY_CLIENT_ID__|$CLIENT_ID|g" $(Pipeline.Workspace)/k8s-manifests/secretproviderclass.yml
                sed -i "s|__TENANT_ID__|$TENANT_ID|g" $(Pipeline.Workspace)/k8s-manifests/secretproviderclass.yml
            displayName: "Inject Key Vault Secrets Provider Identifiers"

          - task: KubernetesManifest@1
            inputs:
              action: "deploy"
              connectionType: "azureResourceManager"
              azureSubscriptionConnection: $(azureServiceConnection)
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(k8sCluster)
              namespace: $(k8sNamespace)
              manifests: |
                $(Pipeline.Workspace)/k8s-manifests/namespace.yml
                $(Pipeline.Workspace)/k8s-manifests/secretproviderclass.yml
                $(Pipeline.Workspace)/k8s-manifests/postgres-db.yml
                $(Pipeline.Workspace)/k8s-manifests/configmap.yml
                $(Pipeline.Workspace)/k8s-manifests/deployment.yml
                $(Pipeline.Workspace)/k8s-manifests/service.yml
