---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hestia-loyalty-staging-config
  namespace: hestia-staging
data:
  PORT: "3000"
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  HOSTNAME: "0.0.0.0"
