---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hestia-kv-secrets
  namespace: hestia-staging

spec:
  provider: "azure"
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "__IDENTITY_CLIENT_ID__"
    keyvaultName: "kv-hestia-staging"
    tenantId: "__TENANT_ID__"
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: auth-secret
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
  secretObjects:
    - secretName: hestia-loyalty-staging-secrets
      type: Opaque
      data:
        - objectName: database-url
          key: DATABASE_URL
        - objectName: auth-secret
          key: AUTH_SECRET
        - objectName: db-password
          key: POSTGRES_PASSWORD
